FROM node:20-bullseye

WORKDIR /app

ENV ROLLUP_NO_NATIVE=1

COPY package.json package-lock.json ./

RUN npm ci --no-audit --no-fund --ignore-scripts

COPY . .

EXPOSE 4200
CMD ["npx", "ng", "serve", "--host=0.0.0.0", "--poll=2000"]
